name: Firebase Hosting
on:
  push:
    branches: [master]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - bin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install
      run: npm install

    - name: Build
      run: |
        npm run firebase:config ${{ secrets.FIREBASE_PROJECT_ID }}
        npm run build

    - name: Deploy
      run: |
        npm install -g firebase-tools
        firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
